name: 'Swift Env'
description: 'A GitHub Action that sets up a Swift environment for cross-platform'
author: 'Koichi Yokota'
branding:
  icon: 'package'
  color: 'purple'

inputs:
  swift-version:
    description: 'Swift version to use'
    required: true
    default: '6.0.3'
  winsdk-version:
    description: 'WinSDK version to use on Windows'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Swift ${{ inputs.swift-version }}
      if: runner.os == 'macOS'
      shell: bash
      run: |
        SWIFT_VERSION=${{ inputs.swift-version }} ./actions/gha-swift-macos.sh
    - name: Set up Swift ${{ inputs.swift-version }}
      if: runner.os == 'Linux'
      shell: bash
      run: |
        SWIFT_VERSION=${{ inputs.swift-version }} ./actions/gha-swift-linux.sh
    - name: Set up Swift ${{ inputs.swift-version }}
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ./actions/GHASwiftWindows.ps1 -SwiftVersion '${{ matrix.swift-version }}' -WinSDK '${{ inputs.winsdk-version }}'
